# Generated by Django 3.0.3 on 2020-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200816_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='user/unknown.jpg', null=True, upload_to='user/'),
        ),
    ]
