# Generated by Django 3.0.3 on 2020-09-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200818_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_to', models.IntegerField()),
                ('followed_by', models.IntegerField()),
            ],
        ),
    ]
