# Generated by Django 3.0.3 on 2020-09-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('followed_to', 'followed_by')},
        ),
    ]
