# Generated by Django 3.0.3 on 2020-06-26 05:28

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conditionaldescription',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='ProdoctImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.ImageField(upload_to='product/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidingprice', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], max_length=20)),
                ('minimumprice', models.FloatField()),
                ('postdate', models.DateField(auto_now=True)),
                ('lastbiddate', models.DateField()),
                ('cover_image', models.ImageField(upload_to='converimage/')),
                ('dayused', models.PositiveIntegerField(blank=True, null=True)),
                ('conditionaldescription', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
