# Generated by Django 3.0.3 on 2020-08-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200711_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='conditionaldescription',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='dayused',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='lastbiddate',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='minimumprice',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='postdate',
        ),
    ]
