# Generated by Django 3.0.3 on 2020-08-13 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_auto_20200808_1128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bidding',
            unique_together={('post', 'user')},
        ),
    ]
