# Generated by Django 3.0.3 on 2020-08-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200813_1718'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bidding',
            unique_together=set(),
        ),
    ]
