# Generated by Django 3.0.3 on 2020-08-31 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0014_auto_20200831_1806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bidding',
            unique_together={('post', 'user')},
        ),
    ]
