# Generated by Django 3.0.3 on 2020-08-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200831_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
