# Generated by Django 3.0.3 on 2020-09-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_bidding_first_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
