# Generated by Django 3.0.3 on 2020-09-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20200901_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lastbiddate',
            field=models.DateTimeField(),
        ),
    ]
